name: artifact

on:
  push:
    branches: [ b1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: demo.txt
        path: demo.txt
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: demo.txt
    - name: print path
      run: pwd
    - name: print contents
      run: ls -la        
